import Head from 'next/head'
import Intro from "@/app/components/screens/home/Intro/Intro";
import About from '@/app/components/screens/home/About/About';

const Index = () => {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Intro />
                <About />
            </main>
        </>
    )
}

export default Index;