import * as React from 'react'
import Head from 'next/head'
import Intro from "@/app/components/screens/home/Intro/Intro";
import About from '@/app/components/screens/home/About/About';
import Loader from '@/app/components/ui/loader/Loader';

const Index = () => {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@400;600;700&family=Playfair+Display:ital,wght@0,500;0,800;1,400;1,600;1,700&display=swap" rel="stylesheet" />
            </Head>
            <main>
                <Intro />
                <About />
            </main>
        </>
    )
}

export default Index;